apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: perbak_app_api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
          - name: client_id
            valueFrom:
              secretKeyRef:
                name: perbak-secrets
                key: client_id
          - name: tenant_id
            valueFrom:
              secretKeyRef:
                name: perbak-secrets
                key: tenant_id
          - name: client_secret
            valueFrom:
              secretKeyRef:
                name: perbak-secrets
                key: client_secret
          - name: vault_url
            valueFrom:
              secretKeyRef:
                name: perbak-secrets
                key: key_vault
