"""prices-added-adj-open

Revision ID: 220de74a4df0
Revises: abcc685866df
Create Date: 2023-01-16 15:40:35.509804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220de74a4df0'
down_revision = 'abcc685866df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('adj_open', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'adj_open')
    # ### end Alembic commands ###
