"""prices updated migration

Revision ID: abcc685866df
Revises: 1
Create Date: 2023-01-16 14:24:31.970306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abcc685866df'
down_revision = '1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('adj_close', sa.Float(), nullable=True))
    op.add_column('prices', sa.Column('adj_high', sa.Float(), nullable=True))
    op.add_column('prices', sa.Column('adj_low', sa.Float(), nullable=True))
    op.add_column('prices', sa.Column('split_factor', sa.Float(), nullable=True))
    op.alter_column('prices', 'open',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('prices', 'high',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('prices', 'low',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('prices', 'close',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('prices', 'volume',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'volume',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('prices', 'close',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('prices', 'low',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('prices', 'high',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('prices', 'open',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('prices', 'split_factor')
    op.drop_column('prices', 'adj_low')
    op.drop_column('prices', 'adj_high')
    op.drop_column('prices', 'adj_close')
    # ### end Alembic commands ###
