apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-deployment
  labels:
    app: etl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl
  template:
    metadata:
      labels:
        app: etl
    spec:
      containers:
      - name: etl
        image: %%VAULT_URL%%/perbak_app_etl_service
        imagePullPolicy: IfNotPresent
        env:
          - name: client_id
            valueFrom:
              secretKeyRef:
                name: perbak-secrets
                key: client_id
          - name: tenant_id
            valueFrom:
              secretKeyRef:
                name: perbak-secrets
                key: tenant_id
          - name: client_secret
            valueFrom:
              secretKeyRef:
                name: perbak-secrets
                key: client_secret
          - name: vault_url
            valueFrom:
              secretKeyRef:
                name: perbak-secrets
                key: key_vault