apiVersion: batch/v1
kind: CronJob
metadata:
  name: etl-cron-job
spec:
  schedule: "0 10 * * 2-6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: etl
              image: %%VAULT_URL%%/perbak_app_etl_service
              imagePullPolicy: IfNotPresent
              env:
                - name: client_id
                  valueFrom:
                    secretKeyRef:
                      name: perbak-secrets
                      key: client_id
                - name: tenant_id
                  valueFrom:
                    secretKeyRef:
                      name: perbak-secrets
                      key: tenant_id
                - name: client_secret
                  valueFrom:
                    secretKeyRef:
                      name: perbak-secrets
                      key: client_secret
                - name: vault_url
                  valueFrom:
                    secretKeyRef:
                      name: perbak-secrets
                      key: key_vault
              command: ["/bin/sh"]
              args:
                - -c
                - >-
                    python etl_service/main.py prices $(date --date='yesterday' +\%Y-\%m-\%d)
          restartPolicy: Never