name: Services Deployment

on:
  push:
    branches:
      - staging

env:
  client_id: ${{ secrets.client_id }}
  tenant_id: ${{ secrets.tenant_id }}
  client_secret: ${{ secrets.client_secret }}
  vault_url: ${{ secrets.vault_url }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
        pytest etl_service/tests/unit

    - name: Build Docker image
      run: docker-compose up --build

    - name: Login to Azure
      run: az login --service-principal -u $client_id -p $client_secret --tenant $tenant_id

    - name: Login to Azure Container Registry
      run: |
        az acr login --name PerbakRegistryStaging

    - name: Deploy to AKS
      run: |
        docker tag perbak_app_etl_service perbakregistrystaging.azurecr.io/perbak_app_etl_service:latest
        docker push perbakregistrystaging.azurecr.io/perbak_app_etl_service:latest
        docker tag perbak_app_api perbakregistrystaging.azurecr.io/perbak_app_api:latest
        docker push perbakregistrystaging.azurecr.io/perbak_app_api:latest

    - name: Download kubeconfig from AKS
      id: get_credentials
      run: |
        az aks get-credentials --resource-group perbak-app-staging --name perbak_cluster_staging --file kubeconfig.yaml
        echo "::set-output name=kubeconfig::$(cat kubeconfig.yaml)"

    - name: Substitute variables in deployment files
      run: |
        sed -i -e "s#%%VAULT_URL%%#perbakregistrystaging.azurecr.io#" etl_service/k8s/etl_cron.yaml
        sed -i -e "s#%%VAULT_URL%%#perbakregistrystaging.azurecr.io#" perbak_api/k8s/deployment.yaml

    - name: Deploy api and etl to Kubernetes
      run: |
        kubectl --kubeconfig=kubeconfig.yaml  apply -f etl_service/k8s/etl_cron.yaml -n perbak-api
        kubectl --kubeconfig=kubeconfig.yaml  apply -f perbak_api/k8s/deployment.yaml -f perbak_api/k8s/service.yaml -n perbak-api